function [cir, rawIqRms] = compute_gnss_code_domain_cir_snapshot( ...
    rawIq, localCode, delaySamples, samplingRateHz, ...
    carrierFrequencyHz, timeOffsetS, navSigns)
%COMPUTE_GNSS_CODE_DOMAIN_CIR_SNAPSHOT Estimate one raw-scale 1 ms CIR row.

rawIq = rawIq(:);
localCode = localCode(:);
navSigns = navSigns(:);
delaySamples = double(delaySamples(:).');
sampleCount = numel(rawIq);

assert(sampleCount >= 2 && numel(localCode) == sampleCount ...
    && numel(navSigns) == sampleCount, ...
    'GNSS:SAGE:SnapshotLengthMismatch', ...
    'IQ, local-code, and navigation-sign vectors must have equal length.');
assert(isfinite(samplingRateHz) && samplingRateHz > 0 ...
    && isfinite(carrierFrequencyHz) && isfinite(timeOffsetS), ...
    'GNSS:SAGE:InvalidSnapshotReference', ...
    'Sampling rate and tracking reference must be finite.');
assert(all(isfinite(real(rawIq))) && all(isfinite(imag(rawIq))) ...
    && all(isfinite(real(localCode))) && all(isfinite(imag(localCode))) ...
    && all(ismember(navSigns, [-1, 1])) ...
    && all(isfinite(delaySamples)), ...
    'GNSS:SAGE:InvalidSnapshotSamples', ...
    'Snapshot vectors and delay grid must contain finite valid values.');

rawIqRms = sqrt(mean(abs(rawIq).^2));
assert(isfinite(rawIqRms) && rawIqRms > 0, ...
    'GNSS:SAGE:InvalidRawIqRms', ...
    'Raw-IQ RMS must be finite and positive.');

sampleTimeS = timeOffsetS + (0:sampleCount - 1).' / samplingRateHz;
observed = rawIq .* navSigns;
observed = observed - mean(observed);
observed = observed .* exp(-1j * 2 * pi ...
    * carrierFrequencyHz * sampleTimeS);

integerCorrelation = ifft(fft(observed) .* conj(fft(localCode)));
integerDelays = -5:40;
integerIndices = mod(integerDelays, sampleCount) + 1;
integerValues = integerCorrelation(integerIndices);
cir = interp1(integerDelays, integerValues, delaySamples, 'pchip');
cir = cir / sampleCount;
end
