function summary = export_gnss_code_domain_cir( ...
    rawIqPath, stage0WindowsCsvPath, stage2SelectedPathsCsvPath, ...
    sceneMetadataPath, outputH5Path, metadataJsonPath, ...
    delayComparisonCsvPath, provenance)
%EXPORT_GNSS_CODE_DOMAIN_CIR Create raw-scale, Stage0-aligned CIR sidecars.

requiredProvenance = {'project_root', 'run_id', 'scene_id', 'prn', ...
    'tracking_channel', 'sample_rate_hz', 'frozen_sage_sha256', ...
    'raw_iq_size_bytes'};
assert(all(isfield(provenance, requiredProvenance)), ...
    'GNSS:SAGE:CIRProvenanceMissing', ...
    'Required run provenance is incomplete.');
assert(strcmp(provenance.scene_id, 'F1023_V70_D0117_P2') ...
    && strcmp(provenance.prn, 'G28') ...
    && double(provenance.tracking_channel) == 1 ...
    && double(provenance.sample_rate_hz) == 10230000 ...
    && strcmpi(provenance.frozen_sage_sha256, ...
    'bffc123c97af77f0a797f417d3866e9a34feab7729c5c1575352f53bc3571b9c'), ...
    'GNSS:SAGE:CIRScopeMismatch', ...
    'CIR export is restricted to the approved F1023/G28/ch1 task.');
assert(isfile(rawIqPath) && isfile(stage0WindowsCsvPath) ...
    && isfile(stage2SelectedPathsCsvPath) ...
    && isfile(sceneMetadataPath), ...
    'GNSS:SAGE:CIRInputMissing', ...
    'Required target-scene CIR input is missing.');
assert(~isfile(outputH5Path) && ~isfile(metadataJsonPath) ...
    && ~isfile(delayComparisonCsvPath), ...
    'GNSS:SAGE:CIROutputCollision', ...
    'Refusing to overwrite an existing CIR sidecar or comparison.');

rawInfo = dir(rawIqPath);
assert(rawInfo.bytes == double(provenance.raw_iq_size_bytes) ...
    && rawInfo.bytes > 0, ...
    'GNSS:SAGE:RawIqSizeMismatch', ...
    'Raw-IQ size changed; SHA-256 is intentionally not recomputed.');
sceneMetadataText = readUtf8Text(sceneMetadataPath);
sceneMetadata = jsondecode(sceneMetadataText);
assert(strcmp(sceneMetadata.scene_id, provenance.scene_id) ...
    && double(sceneMetadata.signal.sample_rate_hz) ...
    == double(provenance.sample_rate_hz), ...
    'GNSS:SAGE:SceneMetadataMismatch', ...
    'Scene metadata disagrees with approved run provenance.');
assert(isfield(sceneMetadata.raw_iq, 'path') ...
    && strcmpi(strrep(char(sceneMetadata.raw_iq.path), '/', '\'), ...
    strrep(rawIqPath, '/', '\')) ...
    && isfield(sceneMetadata.signal, 'complex_iq') ...
    && logical(sceneMetadata.signal.complex_iq), ...
    'GNSS:SAGE:RawIqMetadataMismatch', ...
    'Scene metadata raw-IQ path/complex format disagrees with the input.');
metadataTextLower = lower(sceneMetadataText);
calibrationEvidenceFields = {'amplitude_calibration', ...
    'receiver_gain_calibration', 'volts_per_count', 'adc_scale_factor'};
calibrationMetadataFound = any(cellfun( ...
    @(name) contains(metadataTextLower, name), ...
    calibrationEvidenceFields));

coreDirectory = fullfile(provenance.project_root, ...
    'scripts', 'sage_pipeline', 'core');
addpath(coreDirectory);
cfg = default_sage_configuration(28, ...
    double(provenance.sample_rate_hz), false);
delayMaximum = cfg.mainDelayMaximumSamples ...
    + cfg.maximumExcessDelaySamples;
delaySamples = cfg.mainDelayMinimumSamples ...
    : cfg.delayStepSamples : delayMaximum;
assert(numel(delaySamples) == 451 ...
    && abs(delaySamples(1) + 5) < 1e-12 ...
    && abs(delaySamples(end) - 40) < 1e-12, ...
    'GNSS:SAGE:CIRDelayGridMismatch', ...
    'Frozen default configuration did not produce the expected delay grid.');

stageOutputDirectory = fileparts(stage0WindowsCsvPath);
dopplerSignPath = fullfile(stageOutputDirectory, 'doppler_sign.mat');
assert(isfile(dopplerSignPath), ...
    'GNSS:SAGE:DopplerSignMissing', ...
    'Frozen SAGE Doppler-sign evidence is missing.');
dopplerEvidence = load(dopplerSignPath, 'dopplerSignUsed');
assert(isfield(dopplerEvidence, 'dopplerSignUsed') ...
    && ismember(double(dopplerEvidence.dopplerSignUsed), [-1, 1]), ...
    'GNSS:SAGE:DopplerSignInvalid', ...
    'Frozen SAGE Doppler-sign evidence is invalid.');
dopplerSignUsed = double(dopplerEvidence.dopplerSignUsed);

windows = readtable(stage0WindowsCsvPath);
requiredWindowColumns = {'window_id', 'sample_start_zero_based', ...
    'recording_time_s', 'nav_symbol_1', 'nav_symbol_2', ...
    'split_samples', 'tracking_doppler_hz', 'code_frequency_hz', ...
    'cn0_db_hz'};
assert(all(ismember(requiredWindowColumns, ...
    windows.Properties.VariableNames)) && height(windows) > 0, ...
    'GNSS:SAGE:Stage0WindowSchemaMismatch', ...
    'Stage0 window catalog is empty or missing required fields.');

samplesPerMs = cfg.samplesPerMs;
samplesPer40Ms = cfg.samplesPer40Ms;
assert(samplesPerMs == 10230 && samplesPer40Ms == 40 * samplesPerMs, ...
    'GNSS:SAGE:CIRSampleGridMismatch', ...
    'Frozen configuration does not yield exact 1 ms sample blocks.');
snapshotCount = height(windows) * 40;
delayCount = numel(delaySamples);
cirReal = zeros(snapshotCount, delayCount, 'double');
cirImag = zeros(snapshotCount, delayCount, 'double');
rawIqRms = zeros(snapshotCount, 1, 'double');
snapshotTimeS = zeros(snapshotCount, 1, 'double');
snapshotSampleStart = zeros(snapshotCount, 1, 'double');
snapshotWindowId = zeros(snapshotCount, 1, 'uint32');
snapshotIndexInWindow = zeros(snapshotCount, 1, 'uint8');
trackingDopplerHz = zeros(snapshotCount, 1, 'double');
codeFrequencyHz = zeros(snapshotCount, 1, 'double');
cn0DbHz = zeros(snapshotCount, 1, 'double');
navSymbol = zeros(snapshotCount, 1, 'int8');
navTransitionOffset = zeros(snapshotCount, 1, 'int32');
pdpPower = zeros(height(windows), delayCount, 'double');

g1g2Code = generateGpsCaCode(28);
rawFileId = fopen(rawIqPath, 'rb', 'ieee-le');
assert(rawFileId >= 0, 'GNSS:SAGE:RawIqOpenFailed', ...
    'Could not open target raw-IQ file.');
rawCleanup = onCleanup(@() fclose(rawFileId)); %#ok<NASGU>
writePosition = 0;
sampleIndexWithinMs = (0:samplesPerMs - 1).';

for windowIndex = 1:height(windows)
    row = windows(windowIndex, :);
    sampleStart = double(row.sample_start_zero_based);
    splitSamples = round(double(row.split_samples));
    nav1 = double(row.nav_symbol_1);
    nav2 = double(row.nav_symbol_2);
    assert(sampleStart >= 0 && sampleStart == floor(sampleStart) ...
        && splitSamples > 0 && splitSamples < samplesPer40Ms ...
        && ismember(nav1, [-1, 1]) && ismember(nav2, [-1, 1]), ...
        'GNSS:SAGE:Stage0WindowInvalid', ...
        'Invalid Stage0 window identity, split, or navigation symbol.');
    status = fseek(rawFileId, sampleStart * 4, 'bof');
    assert(status == 0, 'GNSS:SAGE:RawIqSeekFailed', ...
        'Could not seek to Stage0 window %d.', double(row.window_id));
    rawInterleaved = fread(rawFileId, 2 * samplesPer40Ms, 'int16=>double');
    assert(numel(rawInterleaved) == 2 * samplesPer40Ms, ...
        'GNSS:SAGE:RawIqShortRead', ...
        'Short target raw-IQ read for Stage0 window %d.', ...
        double(row.window_id));
    rawWindow = complex(rawInterleaved(1:2:end), ...
        rawInterleaved(2:2:end));

    trackedCodeFrequencyHz = double(row.code_frequency_hz);
    if ~isfinite(trackedCodeFrequencyHz) || trackedCodeFrequencyHz <= 0
        trackedCodeFrequencyHz = cfg.nominalCodeRateHz;
    end
    trackedDopplerHz = double(row.tracking_doppler_hz);
    cn0 = double(row.cn0_db_hz);
    assert(isfinite(trackedDopplerHz) && isfinite(cn0), ...
        'GNSS:SAGE:Stage0TrackingValueInvalid', ...
        'Stage0 tracking Doppler and C/N0 must be finite.');
    carrierReferenceHz = dopplerSignUsed * trackedDopplerHz;
    windowCir = complex(zeros(40, delayCount, 'double'));

    for snapshotIndex = 0:39
        offset = snapshotIndex * samplesPerMs;
        sampleRange = offset + (1:samplesPerMs);
        rawSnapshot = rawWindow(sampleRange);
        relativeSamples = offset + sampleIndexWithinMs;
        navSigns = repmat(nav2, samplesPerMs, 1);
        navSigns(relativeSamples < splitSamples) = nav1;
        navAtStart = navSigns(1);
        firstTransition = find(navSigns ~= navAtStart, 1, 'first');
        if isempty(firstTransition)
            transitionOffset = 0;
        else
            transitionOffset = firstTransition - 1;
        end

        globalSampleIndex = relativeSamples;
        chipPhase = mod(globalSampleIndex ...
            * trackedCodeFrequencyHz / cfg.fsHz, 1023);
        chipIndex = floor(chipPhase) + 1;
        localCode = g1g2Code(chipIndex);
        [cirSnapshot, rmsValue] = ...
            compute_gnss_code_domain_cir_snapshot( ...
            rawSnapshot, localCode, delaySamples, cfg.fsHz, ...
            carrierReferenceHz, offset / cfg.fsHz, navSigns);

        writePosition = writePosition + 1;
        windowCir(snapshotIndex + 1, :) = cirSnapshot;
        cirReal(writePosition, :) = real(cirSnapshot);
        cirImag(writePosition, :) = imag(cirSnapshot);
        rawIqRms(writePosition) = rmsValue;
        snapshotTimeS(writePosition) = ...
            (sampleStart + offset) / cfg.fsHz;
        snapshotSampleStart(writePosition) = sampleStart + offset;
        snapshotWindowId(writePosition) = uint32(row.window_id);
        snapshotIndexInWindow(writePosition) = uint8(snapshotIndex + 1);
        trackingDopplerHz(writePosition) = trackedDopplerHz;
        codeFrequencyHz(writePosition) = trackedCodeFrequencyHz;
        cn0DbHz(writePosition) = cn0;
        navSymbol(writePosition) = int8(navAtStart);
        navTransitionOffset(writePosition) = int32(transitionOffset);
    end

    % The Stage0-aligned PDP is the arithmetic mean of 40 one-ms powers.
    pdpPower(windowIndex, :) = mean(abs(windowCir).^2, 1);
    if mod(windowIndex, 50) == 0 || windowIndex == height(windows)
        fprintf('CIR_STAGE0_WINDOWS=%d/%d\n', ...
            windowIndex, height(windows));
    end
end

assert(writePosition == snapshotCount, ...
    'GNSS:SAGE:CIRSnapshotCountMismatch', ...
    'CIR snapshot count does not equal 40 times Stage0 windows.');
assert(all(isfinite(cirReal(:))) && all(isfinite(cirImag(:))) ...
    && all(isfinite(rawIqRms)) && all(rawIqRms > 0) ...
    && all(isfinite(snapshotTimeS)) ...
    && all(isfinite(pdpPower(:))), ...
    'GNSS:SAGE:CIRNonfiniteOutput', ...
    'CIR/PDP contains nonfinite values or nonpositive raw-IQ RMS.');

[~, order] = sortrows([snapshotSampleStart, ...
    double(snapshotWindowId), double(snapshotIndexInWindow)], [1, 2, 3]);
cirReal = cirReal(order, :);
cirImag = cirImag(order, :);
rawIqRms = rawIqRms(order);
snapshotTimeS = snapshotTimeS(order);
snapshotSampleStart = snapshotSampleStart(order);
snapshotWindowId = snapshotWindowId(order);
snapshotIndexInWindow = snapshotIndexInWindow(order);
trackingDopplerHz = trackingDopplerHz(order);
codeFrequencyHz = codeFrequencyHz(order);
cn0DbHz = cn0DbHz(order);
navSymbol = navSymbol(order);
navTransitionOffset = navTransitionOffset(order);
assert(all(diff(snapshotTimeS) >= 0), ...
    'GNSS:SAGE:CIRTimeOrderInvalid', ...
    'CIR time axis is not monotonic nondecreasing.');

pdpTimeS = double(windows.recording_time_s);
pdpWindowId = uint32(windows.window_id);
pdpStartSample = double(windows.sample_start_zero_based);
assert(numel(unique(pdpWindowId)) == height(windows) ...
    && size(pdpPower, 1) == height(windows), ...
    'GNSS:SAGE:Stage0PdpMappingMismatch', ...
    'PDP windows do not map one-to-one to Stage0 window IDs.');

stage2Paths = readtable(stage2SelectedPathsCsvPath);
primaryRows = stage2Paths(double(stage2Paths.path_id) == 1, :);
comparison = table(zeros(height(primaryRows), 1), ...
    zeros(height(primaryRows), 1), zeros(height(primaryRows), 1), ...
    zeros(height(primaryRows), 1), zeros(height(primaryRows), 1), ...
    'VariableNames', {'window_id', 'recording_time_s', ...
    'sage_primary_delay_samples', ...
    'pdp_dominant_peak_delay_samples', ...
    'pdp_minus_sage_delay_samples'});
for rowIndex = 1:height(primaryRows)
    windowId = double(primaryRows.window_id(rowIndex));
    matches = find(double(windows.window_id) == windowId);
    assert(numel(matches) == 1, ...
        'GNSS:SAGE:CIRStage2WindowMappingMismatch', ...
        'Stage2 primary path does not map to one Stage0 window.');
    [~, peakIndex] = max(pdpPower(matches, :));
    comparison.window_id(rowIndex) = windowId;
    comparison.recording_time_s(rowIndex) = ...
        double(primaryRows.recording_time_s(rowIndex));
    comparison.sage_primary_delay_samples(rowIndex) = ...
        double(primaryRows.delay_samples(rowIndex));
    comparison.pdp_dominant_peak_delay_samples(rowIndex) = ...
        delaySamples(peakIndex);
    comparison.pdp_minus_sage_delay_samples(rowIndex) = ...
        comparison.pdp_dominant_peak_delay_samples(rowIndex) ...
        - comparison.sage_primary_delay_samples(rowIndex);
end
assert(height(comparison) > 0 ...
    && all(isfinite(comparison.pdp_minus_sage_delay_samples)), ...
    'GNSS:SAGE:CIRDelayComparisonInvalid', ...
    'Primary SAGE/CIR delay comparison is empty or nonfinite.');

temporaryH5Path = [tempname(fileparts(outputH5Path)), '.h5'];
temporaryMetadataPath = [tempname(fileparts(metadataJsonPath)), '.json'];
temporaryComparisonPath = [tempname(fileparts(delayComparisonCsvPath)), '.csv'];
createAndWriteHdf5(temporaryH5Path, delaySamples, snapshotTimeS, ...
    cirReal, cirImag, rawIqRms, trackingDopplerHz, codeFrequencyHz, ...
    cn0DbHz, navSymbol, snapshotWindowId, snapshotIndexInWindow, ...
    snapshotSampleStart, navTransitionOffset, pdpWindowId, pdpTimeS, ...
    pdpStartSample, pdpPower);
writetable(comparison, temporaryComparisonPath);

absoluteDifference = abs(comparison.pdp_minus_sage_delay_samples);
summary = struct( ...
    'scene_id', provenance.scene_id, ...
    'prn', provenance.prn, ...
    'tracking_channel', double(provenance.tracking_channel), ...
    'sample_rate_hz', double(provenance.sample_rate_hz), ...
    'stage0_window_count', height(windows), ...
    'cir_snapshot_count', snapshotCount, ...
    'unique_cir_snapshot_start_samples', ...
        numel(unique(snapshotSampleStart)), ...
    'delay_grid_count', delayCount, ...
    'delay_grid_min_samples', delaySamples(1), ...
    'delay_grid_max_samples', delaySamples(end), ...
    'pdp_window_count', height(windows), ...
    'pdp_snapshots_per_window', 40, ...
    'time_monotonic_nondecreasing', true, ...
    'raw_iq_sha256_status', 'NOT_RECOMPUTED', ...
    'doppler_sign_used', dopplerSignUsed, ...
    'amplitude_reference_status', ...
        'UNKNOWN_RECEIVER_GAIN_OR_AGC', ...
    'primary_delay_comparison_count', height(comparison), ...
    'primary_delay_difference_max_abs_samples', max(absoluteDifference), ...
    'primary_delay_difference_median_samples', ...
        median(comparison.pdp_minus_sage_delay_samples));

metadata = struct();
metadata.format_version = 1;
metadata.created_utc = char(datetime('now', 'TimeZone', 'UTC'));
metadata.created_time_zone = 'UTC';
metadata.run_id = provenance.run_id;
metadata.scene_id = provenance.scene_id;
metadata.prn = provenance.prn;
metadata.tracking_channel = double(provenance.tracking_channel);
metadata.sample_rate_hz = double(provenance.sample_rate_hz);
metadata.raw_iq_path = rawIqPath;
metadata.raw_iq_size_bytes = rawInfo.bytes;
metadata.raw_iq_sha256 = 'NOT_RECOMPUTED';
metadata.frozen_sage_sha256 = provenance.frozen_sage_sha256;
metadata.doppler_sign_used = dopplerSignUsed;
metadata.delay_grid_samples = delaySamples;
metadata.delay_grid_source = ...
    'default_sage_configuration: mainDelayMinimumSamples:delayStepSamples:(mainDelayMaximumSamples+maximumExcessDelaySamples)';
metadata.cir_definition = ...
    ['One-ms coherent code-domain correlation: samplewise NAV sign wipe; ' ...
    'per-snapshot complex-mean removal; tracking-Doppler wipe using ' ...
    'dopplerSignUsed*tracking_doppler_hz; tracked-rate GPS C/A code; ' ...
    'no per-snapshot RMS normalization; correlation divided by sample count.'];
metadata.fractional_delay_interpolation = ...
    'PCHIP interpolation of integer-delay circular FFT correlations; delay samples are from frozen default configuration.';
metadata.raw_iq_rms_definition = ...
    'sqrt(mean(abs(raw complex int16 IQ)^2)) before NAV wipe, DC removal, or normalization; units are ADC counts.';
metadata.time_axis_semantics = ...
    ['Absolute recording seconds from zero-based raw sample index. ' ...
    'Snapshots are sorted nondecreasing by sample start; overlapping ' ...
    'Stage0 40-ms windows intentionally repeat timestamps under separate window IDs.'];
metadata.pdp_definition = ...
    'For every Stage0 window, arithmetic mean of the powers of its 40 one-ms CIR snapshots; no coherent complex sum.';
metadata.nav_symbol_semantics = ...
    ['nav_symbol is the sign applied to the first sample in each snapshot; ' ...
    'nav_symbol_transition_offset_samples is 0 when there is no in-snapshot ' ...
    'transition and otherwise the number of leading samples using that sign.'];
metadata.amplitude_reference_status = ...
    'UNKNOWN_RECEIVER_GAIN_OR_AGC';
metadata.amplitude_calibration_metadata_found = ...
    calibrationMetadataFound;
metadata.stage0_window_count = height(windows);
metadata.cir_snapshot_count = snapshotCount;
metadata.unique_cir_snapshot_start_samples = ...
    numel(unique(snapshotSampleStart));
metadata.delay_grid_count = delayCount;
metadata.pdp_snapshots_per_window = 40;
metadata.primary_delay_comparison = struct( ...
    'count', height(comparison), ...
    'max_abs_difference_samples', max(absoluteDifference), ...
    'median_signed_difference_samples', ...
    median(comparison.pdp_minus_sage_delay_samples), ...
    'csv_path', delayComparisonCsvPath);
metadata.validation = struct( ...
    'cir_all_finite', true, 'raw_iq_rms_all_positive', true, ...
    'time_monotonic_nondecreasing', true, ...
    'delay_grid_fixed', true, ...
    'pdp_stage0_window_one_to_one', true, ...
    'pdp_40ms_arithmetic_mean_of_40_powers', true);

metadataText = jsonencode(metadata);
metadataFileId = fopen(temporaryMetadataPath, 'wt', 'n', 'UTF-8');
assert(metadataFileId >= 0, ...
    'GNSS:SAGE:CIRMetadataWriteFailed', ...
    'Could not create temporary CIR metadata JSON.');
metadataCleanup = onCleanup(@() fclose(metadataFileId)); %#ok<NASGU>
fwrite(metadataFileId, metadataText, 'char');
fwrite(metadataFileId, newline, 'char');
clear metadataCleanup;

assert(~isfile(outputH5Path) && ~isfile(metadataJsonPath) ...
    && ~isfile(delayComparisonCsvPath), ...
    'GNSS:SAGE:CIROutputCollision', ...
    'Refusing to overwrite a CIR sidecar or comparison during publish.');
[moved, message] = movefile(temporaryComparisonPath, ...
    delayComparisonCsvPath);
assert(moved, 'GNSS:SAGE:CIRPublishFailed', ...
    'Could not publish CIR delay comparison CSV: %s', message);
[moved, message] = movefile(temporaryMetadataPath, metadataJsonPath);
assert(moved, 'GNSS:SAGE:CIRPublishFailed', ...
    'Could not publish CIR metadata JSON: %s', message);
[moved, message] = movefile(temporaryH5Path, outputH5Path);
assert(moved, 'GNSS:SAGE:CIRPublishFailed', ...
    'Could not publish CIR HDF5 sidecar: %s', message);

fprintf('CIR_EXPORT_STATUS=COMPLETE\n');
fprintf('CIR_WINDOWS=%d CIR_SNAPSHOTS=%d CIR_DELAYS=%d\n', ...
    summary.stage0_window_count, summary.cir_snapshot_count, ...
    summary.delay_grid_count);
fprintf('CIR_TIME_MONOTONIC_NONDECREASING=%d\n', ...
    summary.time_monotonic_nondecreasing);
fprintf('CIR_PDP_WINDOWS=%d PDP_SNAPSHOTS_PER_WINDOW=%d\n', ...
    summary.pdp_window_count, summary.pdp_snapshots_per_window);
fprintf('CIR_PRIMARY_DELAY_COMPARISON_COUNT=%d MAX_ABS_DIFF_SAMPLES=%.12g\n', ...
    summary.primary_delay_comparison_count, ...
    summary.primary_delay_difference_max_abs_samples);
end

function createAndWriteHdf5(filename, delaySamples, timeS, ...
    cirReal, cirImag, rawIqRms, trackingDopplerHz, codeFrequencyHz, ...
    cn0DbHz, navSymbol, windowId, snapshotIndex, sampleStart, ...
    navTransitionOffset, pdpWindowId, pdpTimeS, pdpStartSample, pdpPower)
nSnapshots = numel(timeS);
nDelays = numel(delaySamples);
nWindows = numel(pdpWindowId);
createMatrix(filename, '/cir_real', cirReal, [min(40, nSnapshots), nDelays]);
createMatrix(filename, '/cir_imag', cirImag, [min(40, nSnapshots), nDelays]);
createMatrix(filename, '/pdp_power', pdpPower, [min(16, nWindows), nDelays]);
createVector(filename, '/time_s', timeS, 'double');
createVector(filename, '/delay_samples', delaySamples, 'double');
createVector(filename, '/raw_iq_rms', rawIqRms, 'double');
createVector(filename, '/tracking_doppler_hz', trackingDopplerHz, 'double');
createVector(filename, '/code_frequency_hz', codeFrequencyHz, 'double');
createVector(filename, '/cn0_db_hz', cn0DbHz, 'double');
createVector(filename, '/nav_symbol', navSymbol, 'int8');
createVector(filename, '/window_id', windowId, 'uint32');
createVector(filename, '/snapshot_index_in_window', ...
    snapshotIndex, 'uint8');
createVector(filename, '/sample_start_zero_based', sampleStart, 'double');
createVector(filename, '/nav_symbol_transition_offset_samples', ...
    navTransitionOffset, 'int32');
createVector(filename, '/pdp_window_id', pdpWindowId, 'uint32');
createVector(filename, '/pdp_time_s', pdpTimeS, 'double');
createVector(filename, '/pdp_start_sample_zero_based', ...
    pdpStartSample, 'double');
createVector(filename, '/pdp_interval_count', ...
    repmat(uint8(40), nWindows, 1), 'uint8');
h5write(filename, '/cir_real', cirReal);
h5write(filename, '/cir_imag', cirImag);
h5write(filename, '/pdp_power', pdpPower);
h5write(filename, '/time_s', timeS(:));
h5write(filename, '/delay_samples', delaySamples(:));
h5write(filename, '/raw_iq_rms', rawIqRms(:));
h5write(filename, '/tracking_doppler_hz', trackingDopplerHz(:));
h5write(filename, '/code_frequency_hz', codeFrequencyHz(:));
h5write(filename, '/cn0_db_hz', cn0DbHz(:));
h5write(filename, '/nav_symbol', navSymbol(:));
h5write(filename, '/window_id', windowId(:));
h5write(filename, '/snapshot_index_in_window', snapshotIndex(:));
h5write(filename, '/sample_start_zero_based', sampleStart(:));
h5write(filename, '/nav_symbol_transition_offset_samples', ...
    navTransitionOffset(:));
h5write(filename, '/pdp_window_id', pdpWindowId(:));
h5write(filename, '/pdp_time_s', pdpTimeS(:));
h5write(filename, '/pdp_start_sample_zero_based', pdpStartSample(:));
h5write(filename, '/pdp_interval_count', ...
    repmat(uint8(40), nWindows, 1));
h5writeatt(filename, '/', 'description', ...
    'GNSS code-domain CIR snapshots and Stage0-aligned 40 ms PDP.');
h5writeatt(filename, '/', 'amplitude_reference_status', ...
    'UNKNOWN_RECEIVER_GAIN_OR_AGC');
h5writeatt(filename, '/', 'delay_samples_semantics', ...
    'Fractional circular code-delay samples; positive sign follows frozen SAGE makeReplica.');
end

function createMatrix(filename, datasetName, values, chunkSize)
h5create(filename, datasetName, size(values), ...
    'Datatype', 'double', 'ChunkSize', chunkSize, 'Deflate', 1);
end

function createVector(filename, datasetName, values, dataType)
values = values(:);
h5create(filename, datasetName, [numel(values), 1], ...
    'Datatype', dataType, ...
    'ChunkSize', [min(1024, numel(values)), 1], 'Deflate', 1);
end

function caCode = generateGpsCaCode(prn)
g2TapTable = [ ...
    2,6; 3,7; 4,8; 5,9; 1,9; 2,10; 1,8; 2,9; ...
    3,10; 2,3; 3,4; 5,6; 6,7; 7,8; 8,9; 9,10; ...
    1,4; 2,5; 3,6; 4,7; 5,8; 6,9; 1,3; 4,6; ...
    5,7; 6,8; 7,9; 8,10; 1,6; 2,7; 3,8; 4,9];
assert(prn >= 1 && prn <= size(g2TapTable, 1), ...
    'GNSS:SAGE:UnsupportedPrn', 'Unsupported GPS PRN: %d', prn);
g1 = -ones(1, 10);
g2 = -ones(1, 10);
caCode = zeros(1023, 1);
taps = g2TapTable(prn, :);
for index = 1:1023
    caCode(index) = g1(10) * g2(taps(1)) * g2(taps(2));
    g1Feedback = g1(3) * g1(10);
    g2Feedback = g2(2) * g2(3) * g2(6) ...
        * g2(8) * g2(9) * g2(10);
    g1 = [g1Feedback, g1(1:9)]; %#ok<AGROW>
    g2 = [g2Feedback, g2(1:9)]; %#ok<AGROW>
end
end

function text = readUtf8Text(filename)
fileId = fopen(filename, 'rb');
assert(fileId >= 0, 'GNSS:SAGE:MetadataOpenFailed', ...
    'Could not open scene metadata JSON.');
fileCleanup = onCleanup(@() fclose(fileId)); %#ok<NASGU>
bytes = fread(fileId, inf, '*uint8').';
if numel(bytes) >= 3 ...
        && isequal(bytes(1:3), uint8([239, 187, 191]))
    bytes = bytes(4:end);
end
text = native2unicode(bytes, 'UTF-8');
clear fileCleanup;
end
