function result = build_rain_stage0(sceneId, prn, varargin)
%BUILD_RAIN_STAGE0 Build a NAV-aided Stage0 catalog without NMEA/PVT.
%
% This is the Rain input adapter only. It reads metadata, the GNSS-SDR
% telemetry DAT, and the tracking MAT. It never opens raw IQ. Stage1-Stage4
% are provided by the branch-local Rain implementation in this folder.
%
% Example:
%   build_rain_stage0("F1023_clear", "G24", ...
%       "TrackingChannel", 10, ...
%       "ProjectRoot", "E:\GNSS_Multipath_Project", ...
%       "OutputDir", "E:\...\rain_sage_v1\G24");

scriptDir = fileparts(mfilename("fullpath"));
addpath(scriptDir, "-begin");

parser = inputParser;
addRequired(parser, "sceneId", @(v) ischar(v) || (isstring(v) && isscalar(v)));
addRequired(parser, "prn", @(v) isnumeric(v) || ischar(v) || ...
    (isstring(v) && isscalar(v)));
addParameter(parser, "TrackingChannel", [], @(v) isnumeric(v) && ...
    isscalar(v) && isfinite(v) && v == round(v) && v >= 0);
addParameter(parser, "ProjectRoot", fileparts(fileparts(fileparts( ...
    mfilename("fullpath")))), @(v) ischar(v) || ...
    (isstring(v) && isscalar(v)));
addParameter(parser, "OutputDir", "", @(v) ischar(v) || ...
    (isstring(v) && isscalar(v)));
addParameter(parser, "WriteOutputs", true, @(v) ...
    (islogical(v) || isnumeric(v)) && isscalar(v));
parse(parser, sceneId, prn, varargin{:});
options = parser.Results;

sceneId = string(options.sceneId);
[prnNumber, prnLabel] = normalizeRainPrn(options.prn);
assert(~isempty(options.TrackingChannel), ...
    "TrackingChannel must be supplied explicitly.");
channel = double(options.TrackingChannel);
projectRoot = string(options.ProjectRoot);
sceneDir = fullfile(projectRoot, "scenes", sceneId);
assert(isfolder(sceneDir), "Rain scene folder not found: %s", sceneDir);

metadataFile = fullfile(sceneDir, "metadata.json");
assert(isfile(metadataFile), "Rain metadata not found: %s", metadataFile);
metadata = jsondecode(fileread(metadataFile));
assert(isfield(metadata, "scene_id") && string(metadata.scene_id) == sceneId, ...
    "Rain metadata scene_id does not match the scene folder.");
assert(isfield(metadata, "branch") && ...
    string(metadata.branch) == "darkroom_channel_emulation", ...
    "Rain Stage0 requires branch=darkroom_channel_emulation.");
assert(isfield(metadata, "signal") && ...
    double(metadata.signal.sample_rate_hz) == 10230000, ...
    "Rain Stage0 supports only 10.23 MHz.");
assert(isfield(metadata, "raw_iq") && isfield(metadata.raw_iq, "path"), ...
    "Rain metadata.raw_iq.path is missing.");

rawFile = string(metadata.raw_iq.path);
rawInfo = dir(rawFile);
assert(isscalar(rawInfo) && rawInfo.bytes > 0, ...
    "Rain raw IQ metadata path is missing or empty: %s", rawFile);

gnssSdrDir = fullfile(sceneDir, "gnss_sdr");
telemetryFile = fullfile(gnssSdrDir, "telemetry", ...
    sprintf("%s_telemetry_ch_%d.dat", sceneId, channel));
trackingFile = fullfile(gnssSdrDir, "tracking", ...
    sprintf("%s_track_ch_%d.mat", sceneId, channel));
assert(isfile(telemetryFile), "Rain telemetry file not found: %s", telemetryFile);
assert(isfile(trackingFile), "Rain tracking MAT file not found: %s", trackingFile);
trackingInfo = dir(trackingFile);
assert(isscalar(trackingInfo) && trackingInfo.bytes > 0, ...
    "Rain tracking MAT file is empty: %s", trackingFile);

if strlength(string(options.OutputDir)) == 0
    outputDir = fullfile(sceneDir, "sage_results", ...
        "rain_sage_v1", prnLabel);
else
    outputDir = string(options.OutputDir);
end

cfg = rainStage0Configuration(prnNumber, 10230000);
cfg.sceneId = char(sceneId);
cfg.prnLabel = char(prnLabel);
cfg.trackingChannel = channel;
telemetry = readRainTelemetryDat(telemetryFile);
tracking = readRainTrackingMat(trackingFile);
assert(any(telemetry.prn == cfg.targetPrn), ...
    "Requested PRN %s is not present in the telemetry mapping.", prnLabel);

symbolCatalog = buildRainSymbolCatalog(telemetry, tracking, cfg);
windowCatalog = buildRainFortyMsCatalog(symbolCatalog, cfg);
assert(~isempty(symbolCatalog), "No valid Rain NAV symbols for %s.", prnLabel);
assert(~isempty(windowCatalog), "No complete Rain 40 ms windows for %s.", prnLabel);

provenance = struct( ...
    "scene_id", char(sceneId), ...
    "branch", "darkroom_channel_emulation", ...
    "weather_condition", char(erase(sceneId, "F1023_")), ...
    "prn", prnLabel, ...
    "tracking_channel", channel, ...
    "sample_rate_hz", cfg.fsHz, ...
    "raw_iq_opened", false, ...
    "nmea_available", false, ...
    "pvt_available", false, ...
    "trajectory_available", false, ...
    "geometry_available", false, ...
    "elevation_conditioning", false, ...
    "stage1_stage4_implementation", "standalone_rain_branch_local" );

if logical(options.WriteOutputs)
    if ~isfolder(outputDir)
        mkdir(outputDir);
    end
    writetable(symbolCatalog, fullfile(outputDir, ...
        "stage0_valid_symbols.csv"));
    writetable(windowCatalog, fullfile(outputDir, ...
        "stage0_valid_40ms_windows.csv"));
    save(fullfile(outputDir, "stage0_nav_catalog.mat"), ...
        "symbolCatalog", "windowCatalog", "cfg", "provenance");
    jsonText = jsonencode(provenance);
    fileId = fopen(fullfile(outputDir, "rain_stage0_provenance.json"), ...
        "w", "n", "UTF-8");
    assert(fileId >= 0, "Cannot write Rain Stage0 provenance.");
    cleanup = onCleanup(@() fclose(fileId)); %#ok<NASGU>
    fwrite(fileId, jsonText, "char");
end

result = struct( ...
    "scene_id", sceneId, ...
    "prn", prnLabel, ...
    "tracking_channel", channel, ...
    "output_dir", string(outputDir), ...
    "raw_file", rawFile, ...
    "cfg", cfg, ...
    "symbolCatalog", symbolCatalog, ...
    "windowCatalog", windowCatalog, ...
    "provenance", provenance);
end


function cfg = rainStage0Configuration(targetPrn, samplingRateHz)
cfg = default_rain_sage_configuration(targetPrn, samplingRateHz, false);
end


function telemetry = readRainTelemetryDat(filename)
fileId = fopen(filename, "rb", "ieee-le");
assert(fileId >= 0, "Cannot open Rain telemetry file: %s", filename);
cleanup = onCleanup(@() fclose(fileId)); %#ok<NASGU>
fileInfo = dir(filename);
recordBytes = 32;
assert(mod(fileInfo.bytes, recordBytes) == 0, ...
    "Rain telemetry file is not a multiple of 32 bytes.");
recordCount = fileInfo.bytes / recordBytes;
towCurrentS = nan(recordCount, 1);
sampleCounter = zeros(recordCount, 1, "uint64");
towPreambleS = nan(recordCount, 1);
navSymbol = zeros(recordCount, 1, "int32");
prn = zeros(recordCount, 1, "int32");
for index = 1:recordCount
    towCurrentS(index) = fread(fileId, 1, "double=>double");
    sampleCounter(index) = fread(fileId, 1, "uint64=>uint64");
    towPreambleS(index) = fread(fileId, 1, "double=>double");
    navSymbol(index) = fread(fileId, 1, "int32=>int32");
    prn(index) = fread(fileId, 1, "int32=>int32");
end
telemetry = table(towCurrentS, sampleCounter, towPreambleS, ...
    navSymbol, prn, "VariableNames", ...
    {"tow_s", "sample_counter", "preamble_tow_s", "nav_symbol", "prn"});
end


function tracking = readRainTrackingMat(filename)
data = load(filename);
tracking = struct();
tracking.sample = double(pickRainVector(data, ...
    {"PRN_start_sample_count", "PRN_start_sample_counter"}, true));
tracking.prn = double(pickRainVector(data, {"PRN"}, true));
tracking.doppler = double(pickRainVector(data, ...
    {"carrier_doppler_hz"}, true));
tracking.codeFreq = double(pickRainVector(data, ...
    {"code_freq_chips"}, true));
tracking.cn0 = double(pickRainVector(data, ...
    {"CN0_SNV_dB_Hz", "CN0_dB_Hz"}, true));
tracking.lock = double(pickRainVector(data, ...
    {"carrier_lock_test"}, false));
tracking.towMs = double(pickRainVector(data, {"TOW_ms"}, false));
n = numel(tracking.sample);
tracking.prn = padRainVector(tracking.prn, n, nan);
tracking.doppler = padRainVector(tracking.doppler, n, nan);
tracking.codeFreq = padRainVector(tracking.codeFreq, n, nan);
tracking.cn0 = padRainVector(tracking.cn0, n, nan);
tracking.lock = padRainVector(tracking.lock, n, nan);
tracking.towMs = padRainVector(tracking.towMs, n, 0);
end


function catalog = buildRainSymbolCatalog(telemetry, tracking, cfg)
records = repmat(emptyRainSymbolRecord(), 0, 1);
for index = 1:height(telemetry)
    if telemetry.prn(index) ~= cfg.targetPrn || ...
            ~ismember(double(telemetry.nav_symbol(index)), [-1, 1])
        continue;
    end
    sample = double(telemetry.sample_counter(index));
    [sampleError, trackIndex] = min(abs(tracking.sample - sample));
    if isempty(trackIndex) || sampleError > cfg.sampleStepTolerance
        continue;
    end
    if tracking.prn(trackIndex) ~= cfg.targetPrn || ...
            ~isfinite(tracking.doppler(trackIndex)) || ...
            tracking.cn0(trackIndex) < cfg.minimumCn0DbHz
        continue;
    end
    if isfinite(tracking.lock(trackIndex)) && ...
            tracking.lock(trackIndex) < cfg.minimumCarrierLock
        continue;
    end
    continuousToNext = false;
    nextStepSamples = nan;
    nextTowStepS = nan;
    if index < height(telemetry)
        nextStepSamples = double(telemetry.sample_counter(index + 1) ...
            - telemetry.sample_counter(index));
        nextTowStepS = telemetry.tow_s(index + 1) ...
            - telemetry.tow_s(index);
        continuousToNext = telemetry.prn(index + 1) == cfg.targetPrn ...
            && ismember(double(telemetry.nav_symbol(index + 1)), [-1, 1]) ...
            && abs(nextStepSamples - cfg.samplesPer20Ms) ...
                <= cfg.sampleStepTolerance ...
            && abs(nextTowStepS - 0.020) <= cfg.towStepToleranceS;
    end
    records(end + 1, 1) = struct( ... %#ok<AGROW>
        "symbol_id", numel(records) + 1, ...
        "telemetry_row", index, ...
        "prn", cfg.targetPrn, ...
        "tow_s", telemetry.tow_s(index), ...
        "sample_start_zero_based", sample, ...
        "recording_time_s", sample / cfg.fsHz, ...
        "nav_symbol", double(telemetry.nav_symbol(index)), ...
        "tracking_index", trackIndex, ...
        "tracking_doppler_hz", tracking.doppler(trackIndex), ...
        "code_frequency_hz", tracking.codeFreq(trackIndex), ...
        "cn0_db_hz", tracking.cn0(trackIndex), ...
        "carrier_lock_test", tracking.lock(trackIndex), ...
        "tracking_tow_ms", tracking.towMs(trackIndex), ...
        "next_step_samples", nextStepSamples, ...
        "next_tow_step_s", nextTowStepS, ...
        "continuous_to_next", continuousToNext);
end
catalog = struct2table(records);
catalog = sortrows(catalog, "sample_start_zero_based");
catalog.symbol_id = (1:height(catalog)).';
end


function windows = buildRainFortyMsCatalog(symbols, cfg)
records = repmat(emptyRainWindowRecord(), 0, 1);
for index = 1:height(symbols) - 2
    if ~(symbols.continuous_to_next(index) ...
            && symbols.continuous_to_next(index + 1))
        continue;
    end
    if symbols.telemetry_row(index + 1) ~= ...
            symbols.telemetry_row(index) + 1 ...
            || symbols.telemetry_row(index + 2) ~= ...
            symbols.telemetry_row(index) + 2
        continue;
    end
    sampleSteps = diff(symbols.sample_start_zero_based(index:index + 2));
    towSteps = diff(symbols.tow_s(index:index + 2));
    if any(abs(sampleSteps - cfg.samplesPer20Ms) > cfg.sampleStepTolerance) ...
            || any(abs(towSteps - 0.020) > cfg.towStepToleranceS)
        continue;
    end
    speed = nan;
    speedSource = "unavailable_no_NMEA";
    bound = speedToRainDopplerBound(speed, cfg);
    splitSamples = symbols.sample_start_zero_based(index + 1) ...
        - symbols.sample_start_zero_based(index);
    records(end + 1, 1) = struct( ... %#ok<AGROW>
        "window_id", numel(records) + 1, ...
        "symbol_index", index, ...
        "sample_start_zero_based", ...
            symbols.sample_start_zero_based(index), ...
        "recording_time_s", symbols.recording_time_s(index), ...
        "tow_s", symbols.tow_s(index), ...
        "nav_symbol_1", symbols.nav_symbol(index), ...
        "nav_symbol_2", symbols.nav_symbol(index + 1), ...
        "split_samples", splitSamples, ...
        "tracking_doppler_hz", symbols.tracking_doppler_hz(index), ...
        "code_frequency_hz", symbols.code_frequency_hz(index), ...
        "cn0_db_hz", min(symbols.cn0_db_hz(index:index + 1)), ...
        "vehicle_speed_kmh", speed, ...
        "speed_source", speedSource, ...
        "relative_doppler_bound_hz", bound);
end
windows = struct2table(records);
end


function boundHz = speedToRainDopplerBound(speedKmh, cfg)
[boundHz, ~] = compute_rain_doppler_bound(speedKmh, cfg);
end


function [prnNumber, prnLabel] = normalizeRainPrn(prn)
if isnumeric(prn)
    prnNumber = double(prn);
else
    text = upper(strtrim(string(prn)));
    text = erase(text, ["GPS", "PRN", "G"]);
    prnNumber = str2double(text);
end
assert(isfinite(prnNumber) && prnNumber == round(prnNumber) ...
    && prnNumber >= 1 && prnNumber <= 32, ...
    "Rain PRN must identify GPS 1 through 32.");
prnLabel = compose("G%02d", prnNumber);
end


function output = pickRainVector(data, names, required)
output = [];
for index = 1:numel(names)
    if isfield(data, names{index})
        output = data.(names{index});
        output = output(:);
        return;
    end
end
if required
    error("Missing Rain MAT variable. Tried: %s", strjoin(string(names), ", "));
end
end


function output = padRainVector(input, n, fillValue)
if isempty(input)
    output = repmat(fillValue, n, 1);
elseif numel(input) >= n
    output = input(1:n);
else
    output = [input(:); repmat(fillValue, n - numel(input), 1)];
end
end


function record = emptyRainSymbolRecord()
record = struct( ...
    "symbol_id", nan, "telemetry_row", nan, "prn", nan, ...
    "tow_s", nan, "sample_start_zero_based", nan, ...
    "recording_time_s", nan, "nav_symbol", nan, ...
    "tracking_index", nan, "tracking_doppler_hz", nan, ...
    "code_frequency_hz", nan, "cn0_db_hz", nan, ...
    "carrier_lock_test", nan, "tracking_tow_ms", nan, ...
    "next_step_samples", nan, "next_tow_step_s", nan, ...
    "continuous_to_next", false);
end


function record = emptyRainWindowRecord()
record = struct( ...
    "window_id", nan, "symbol_index", nan, ...
    "sample_start_zero_based", nan, "recording_time_s", nan, ...
    "tow_s", nan, "nav_symbol_1", nan, "nav_symbol_2", nan, ...
    "split_samples", nan, "tracking_doppler_hz", nan, ...
    "code_frequency_hz", nan, "cn0_db_hz", nan, ...
    "vehicle_speed_kmh", nan, "speed_source", "", ...
    "relative_doppler_bound_hz", nan);
end
