[CmdletBinding()]
param(
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ProjectRoot = "E:\GNSS_Multipath_Project"
$MatlabExecutable = "D:\Program Files\Matlab\bin\matlab.exe"
$RainDirectory = Join-Path $ProjectRoot "scripts\sage_pipeline\rain"
$RainEntry = Join-Path $RainDirectory "run_rain_sage_pipeline.m"
$InterfaceValidator = Join-Path $RainDirectory "validate_rain_interface.ps1"
$QaHelper = Join-Path $RainDirectory "audit_rain_sage_overnight_outputs.py"
$PreflightCsv = Join-Path $ProjectRoot "dataset_generation_logs\darkroom_channel_emulation\rain_sage_preflight_20260818.csv"
$ProductionEntry = Join-Path $ProjectRoot "scripts\sage_pipeline\run_nav_sage_pipeline.m"
$ProductionFreeze = Join-Path $ProjectRoot "dataset_generation_logs\darkroom_channel_emulation\PRODUCTION_SAGE_PIPELINE_FREEZE.md"
$MonitorRoot = Join-Path $ProjectRoot "dataset_generation_logs\darkroom_channel_emulation"
$ExpectedProductionHash = "BFFC123C97AF77F0A797F417D3866E9A34FEAB7729C5C1575352F53BC3571B9C"
$ExpectedFreezeTag = "sage-production-recovered-validated"
$script:MasterLog = $null
$script:RunDir = $null
$script:PythonExecutable = $null
$script:ProductionHashBefore = $null
$script:PreflightHashBefore = $null
$script:GlobalMutex = $null
$script:MutexAcquired = $false
$script:ExitCode = 0
$script:FormalInitializationComplete = $false
$script:DryRunPlan = $null
$script:QaCsvPath = $null
$script:ParametersCsvPath = $null
$script:QaReportPath = $null
$script:MeetingReportPath = $null

$Tasks = @(
    [pscustomobject]@{ Sequence = 1; Weather = "Clear"; Scene = "F1023_clear"; PRN = "G24"; Channel = 10 },
    [pscustomobject]@{ Sequence = 2; Weather = "Clear"; Scene = "F1023_clear"; PRN = "G29"; Channel = 3 },
    [pscustomobject]@{ Sequence = 3; Weather = "Clear"; Scene = "F1023_clear"; PRN = "G13"; Channel = 8 },
    [pscustomobject]@{ Sequence = 4; Weather = "Clear"; Scene = "F1023_clear"; PRN = "G12"; Channel = 11 },
    [pscustomobject]@{ Sequence = 5; Weather = "MidRain"; Scene = "F1023_midrain"; PRN = "G24"; Channel = 8 },
    [pscustomobject]@{ Sequence = 6; Weather = "MidRain"; Scene = "F1023_midrain"; PRN = "G20"; Channel = 9 },
    [pscustomobject]@{ Sequence = 7; Weather = "HeavyRain"; Scene = "F1023_heavyrain"; PRN = "G02"; Channel = 1 },
    [pscustomobject]@{ Sequence = 8; Weather = "HeavyRain"; Scene = "F1023_heavyrain"; PRN = "G31"; Channel = 4 },
    [pscustomobject]@{ Sequence = 9; Weather = "HeavyRain"; Scene = "F1023_heavyrain"; PRN = "G01"; Channel = 7 }
)

function Write-NewTextFile {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][AllowEmptyString()][AllowNull()][string]$Text
    )
    if ($null -eq $Text) {
        $Text = ""
    }
    $parent = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $parent -PathType Container)) {
        # Windows PowerShell 5.1 New-Item has -Path but not -LiteralPath.
        # These parents are generated by the runner and contain no wildcard
        # characters; all untrusted/input path checks remain LiteralPath-based.
        New-Item -ItemType Directory -Path $parent | Out-Null
    }
    $stream = [System.IO.File]::Open(
        $Path,
        [System.IO.FileMode]::CreateNew,
        [System.IO.FileAccess]::Write,
        [System.IO.FileShare]::None)
    $writer = $null
    try {
        $writer = [System.IO.StreamWriter]::new(
            $stream,
            [System.Text.UTF8Encoding]::new($false))
        $writer.Write($Text)
        $writer.Flush()
    }
    finally {
        if ($null -ne $writer) {
            $writer.Dispose()
        }
        else {
            $stream.Dispose()
        }
    }
}

function Write-NewJson {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][object]$Value
    )
    Write-NewTextFile -Path $Path -Text (($Value | ConvertTo-Json -Depth 20) + [Environment]::NewLine)
}

function Write-Log {
    param([Parameter(Mandatory = $true)][string]$Message)
    $line = "$(Get-Date -Format o) $Message"
    Write-Host $line
    if ($null -ne $script:MasterLog) {
        Add-Content -LiteralPath $script:MasterLog -Value $line -Encoding utf8
    }
}

function Get-FileSha256 {
    param([Parameter(Mandatory = $true)][string]$Path)
    return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant()
}

function Get-CanonicalPath {
    param([Parameter(Mandatory = $true)][string]$Path)
    $full = [System.IO.Path]::GetFullPath($Path)
    return $full.TrimEnd([char[]]@('\', '/'))
}

function Test-PathWithin {
    param(
        [Parameter(Mandatory = $true)][string]$Candidate,
        [Parameter(Mandatory = $true)][string]$Root
    )
    $candidateFull = Get-CanonicalPath -Path $Candidate
    $rootFull = Get-CanonicalPath -Path $Root
    if ($candidateFull.Equals($rootFull, [System.StringComparison]::OrdinalIgnoreCase)) {
        return $true
    }
    return $candidateFull.StartsWith(
        $rootFull + [System.IO.Path]::DirectorySeparatorChar,
        [System.StringComparison]::OrdinalIgnoreCase)
}

function New-UniqueRunDirectory {
    $stamp = (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ")
    for ($index = 0; $index -lt 100; $index++) {
        $suffix = if ($index -eq 0) { "" } else { "_" + $index.ToString("D2") }
        $candidate = Join-Path $MonitorRoot ("rain_sage_overnight_{0}{1}" -f $stamp, $suffix)
        if (Test-Path -LiteralPath $candidate) {
            continue
        }
        try {
            # New-Item -LiteralPath is not available in Windows PowerShell 5.1.
            New-Item -ItemType Directory -Path $candidate | Out-Null
            return $candidate
        }
        catch {
            if (Test-Path -LiteralPath $candidate) {
                continue
            }
            throw
        }
    }
    throw "Unable to create a unique Rain overnight log namespace."
}

function Acquire-GlobalRunnerMutex {
    $script:GlobalMutex = [System.Threading.Mutex]::new(
        $false,
        "Local\GNSS_SAGE_RAIN_SAGE_OVERNIGHT")
    if (-not $script:GlobalMutex.WaitOne(0)) {
        $script:GlobalMutex.Dispose()
        $script:GlobalMutex = $null
        throw "Another Rain overnight runner is already active."
    }
    $script:MutexAcquired = $true
}

function Assert-NormalUserExecutionIdentity {
    $windowsIdentity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    $identity = $windowsIdentity.Name
    if ($identity -match "(?i)codexsandboxoffline") {
        throw "Formal Rain execution is blocked under Codex sandbox identity: $identity. Run from TJ-CHANNEL\Jing_ non-administrator PowerShell."
    }
    if ($identity -notmatch "(?i)^TJ-CHANNEL\\Jing_$") {
        throw "Formal Rain execution requires TJ-CHANNEL\Jing_; actual identity is $identity"
    }
    $principal = [System.Security.Principal.WindowsPrincipal]::new($windowsIdentity)
    if ($principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw "Formal Rain execution must not run from an elevated Administrator shell."
    }
    return $identity
}

function Assert-ProductionFrozen {
    if (-not (Test-Path -LiteralPath $ProductionEntry -PathType Leaf)) {
        throw "Production entry is missing: $ProductionEntry"
    }
    if (-not (Test-Path -LiteralPath $ProductionFreeze -PathType Leaf)) {
        throw "Production freeze record is missing: $ProductionFreeze"
    }
    $hash = Get-FileSha256 -Path $ProductionEntry
    if ($hash -ne $ExpectedProductionHash) {
        throw "Production SHA mismatch: expected $ExpectedProductionHash, actual $hash"
    }
    $freezeText = [System.IO.File]::ReadAllText($ProductionFreeze)
    if ($freezeText -notmatch "PRODUCTION_PIPELINE_FROZEN\s*[:=]\s*YES" -and
        $freezeText -notmatch "PRODUCTION_PIPELINE_FROZEN=YES") {
        throw "Production freeze record does not assert PRODUCTION_PIPELINE_FROZEN=YES"
    }
    $tags = @(& git -C $ProjectRoot tag --list $ExpectedFreezeTag)
    if ($tags -notcontains $ExpectedFreezeTag) {
        throw "Required production freeze tag is missing: $ExpectedFreezeTag"
    }
    $diff = @(& git -C $ProjectRoot diff -- $ProductionEntry)
    if ($diff.Count -ne 0) {
        throw "Production entry has an uncommitted diff."
    }
    return $hash
}

function Assert-RainInterface {
    if (-not (Test-Path -LiteralPath $MatlabExecutable -PathType Leaf)) {
        throw "MATLAB executable is missing: $MatlabExecutable"
    }
    if (-not (Test-Path -LiteralPath $RainEntry -PathType Leaf)) {
        throw "Rain entry is missing: $RainEntry"
    }
    if (-not (Test-Path -LiteralPath $InterfaceValidator -PathType Leaf)) {
        throw "Rain interface validator is missing: $InterfaceValidator"
    }
    . $InterfaceValidator
    $source = [System.IO.File]::ReadAllText($RainEntry)
    $stage14Path = Join-Path $RainDirectory "run_rain_sage_stage1_stage4.m"
    if (-not (Test-Path -LiteralPath $stage14Path -PathType Leaf)) {
        throw "Standalone evaluator is missing: $stage14Path"
    }
    $stage14Source = [System.IO.File]::ReadAllText($stage14Path)
    $interfaceResult = Test-RainInterfaceSource -EntrySource $source -EvaluatorSource $stage14Source -EvaluatorPathExists $true
    if (-not $interfaceResult.Pass) {
        throw "Rain interface validation failed: $($interfaceResult.Reason)"
    }
    foreach ($marker in @(
            "function result = run_rain_sage_pipeline(sceneId, prn, varargin)",
            'addParameter(parser, "TrackingChannel"',
            'addParameter(parser, "ProjectRoot"',
            'addParameter(parser, "Resume"',
            'addParameter(parser, "PreflightOnly"',
            'addParameter(parser, "Stage0Only"',
            'assert(~logical(options.Resume)',
            '"rain_sage_v1"')) {
        if ($source -notmatch [regex]::Escape($marker)) {
            throw "Rain interface marker is missing: $marker"
        }
    }
    if ($source -match "run_sage_stage1_stage4_core|nav_sage_v2") {
        throw "Rain entry references a forbidden production/shared-core route."
    }
}

function Assert-PreflightRow {
    param(
        [Parameter(Mandatory = $true)][object]$Task,
        [Parameter(Mandatory = $true)][object[]]$Rows
    )
    $matches = @($Rows | Where-Object {
        $_.scene -eq $Task.Scene -and $_.prn -eq $Task.PRN -and
        [int]$_.channel -eq [int]$Task.Channel
    })
    if ($matches.Count -ne 1) {
        throw "Expected exactly one static preflight row for $($Task.Scene)/$($Task.PRN)/ch$($Task.Channel); found $($matches.Count)."
    }
    $row = $matches[0]
    if ($row.preflight_pass -ne "PASS_STATIC_INPUT_GATE") {
        throw "Static preflight is not PASS_STATIC_INPUT_GATE for $($Task.Scene)/$($Task.PRN)."
    }
    foreach ($field in @("raw_ready", "tracking_ready", "telemetry_ready", "mapping_ready", "sample_rate_ready", "stage0_input_ready", "output_safe")) {
        if ([string]$row.$field -notin @("True", "true", "1")) {
            throw "Static preflight field $field is not true for $($Task.Scene)/$($Task.PRN)."
        }
    }
    return $row
}

function Assert-ExpectedOutputNamespace {
    param(
        [Parameter(Mandatory = $true)][object]$Task,
        [Parameter(Mandatory = $true)][string]$OutputDir
    )
    $sceneRoot = Join-Path $ProjectRoot ("scenes\{0}" -f $Task.Scene)
    $expected = Join-Path $sceneRoot ("sage_results\rain_sage_v1\{0}" -f $Task.PRN)
    if (-not $OutputDir.Equals($expected, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Unexpected output namespace for $($Task.Scene)/$($Task.PRN): $OutputDir"
    }
    if (-not (Test-PathWithin -Candidate $OutputDir -Root (Join-Path $sceneRoot "sage_results\rain_sage_v1"))) {
        throw "Output namespace escapes Rain root: $OutputDir"
    }
    if ($OutputDir -match "nav_sage_v2") {
        throw "Output namespace points to nav_sage_v2."
    }
    return $expected
}

function New-MatlabExpression {
    param([Parameter(Mandatory = $true)][object]$Task)
    $expression = "addpath('E:/GNSS_Multipath_Project/scripts/sage_pipeline/rain'); result=run_rain_sage_pipeline('$($Task.Scene)','$($Task.PRN)','TrackingChannel',$($Task.Channel),'ProjectRoot','E:/GNSS_Multipath_Project','Resume',false,'PreflightOnly',false,'Stage0Only',false); disp(result);"
    if ($expression -match "(?i)'Resume'\s*,\s*true") {
        throw "Generated MATLAB expression contains Resume=true."
    }
    if ($expression -notmatch "(?i)'Resume'\s*,\s*false") {
        throw "Generated MATLAB expression does not contain Resume=false."
    }
    return $expression
}

function ConvertTo-SafeDiagnosticText {
    param([Parameter(Mandatory = $false)][AllowNull()][object]$Value)
    try {
        if ($null -eq $Value) {
            return ""
        }
        $text = [string]$Value
        return ($text -replace "[\r\n]+", " | ")
    }
    catch {
        return "<unprintable>"
    }
}

function Get-ErrorDiagnosticLines {
    param([Parameter(Mandatory = $false)][AllowNull()][object]$ErrorRecord)
    try {
        $invocation = $null
        $message = ""
        $stack = ""
        $errorId = ""
        $command = ""
        $lineNumber = ""
        $lineText = ""
        $position = ""
        if ($null -ne $ErrorRecord) {
            $invocation = $ErrorRecord.InvocationInfo
            if ($null -ne $ErrorRecord.Exception) {
                $message = ConvertTo-SafeDiagnosticText -Value $ErrorRecord.Exception.Message
            }
            $stack = ConvertTo-SafeDiagnosticText -Value $ErrorRecord.ScriptStackTrace
            $errorId = ConvertTo-SafeDiagnosticText -Value $ErrorRecord.FullyQualifiedErrorId
            if ($null -ne $invocation) {
                if ($null -ne $invocation.MyCommand) {
                    $command = ConvertTo-SafeDiagnosticText -Value $invocation.MyCommand.Name
                }
                $lineNumber = ConvertTo-SafeDiagnosticText -Value $invocation.ScriptLineNumber
                $lineText = ConvertTo-SafeDiagnosticText -Value $invocation.Line
                $position = ConvertTo-SafeDiagnosticText -Value $invocation.PositionMessage
            }
            if ([string]::IsNullOrWhiteSpace($command)) {
                $command = ConvertTo-SafeDiagnosticText -Value $ErrorRecord.CategoryInfo.Activity
            }
        }
        return @(
            "ERROR_MESSAGE=$message",
            "ERROR_COMMAND=$command",
            "ERROR_LINE=$lineText",
            "ERROR_LINE_NUMBER=$lineNumber",
            "ERROR_POSITION=$position",
            "ERROR_SCRIPT_STACK_TRACE=$stack",
            "FULLY_QUALIFIED_ERROR_ID=$errorId",
            "POWERSHELL_VERSION=$(ConvertTo-SafeDiagnosticText -Value $PSVersionTable.PSVersion)"
        )
    }
    catch {
        $fallback = "ERROR_DIAGNOSTICS_INTERNAL_FAILURE=$(ConvertTo-SafeDiagnosticText -Value $_.Exception.Message)"
        return @($fallback)
    }
}

function Write-ErrorDiagnostics {
    param(
        [Parameter(Mandatory = $false)][AllowNull()][object]$ErrorRecord,
        [Parameter(Mandatory = $false)][AllowNull()][System.IO.TextWriter]$Writer
    )
    try {
        $diagnosticLines = @(Get-ErrorDiagnosticLines -ErrorRecord $ErrorRecord)
    }
    catch {
        $diagnosticLines = @("ERROR_DIAGNOSTICS_INTERNAL_FAILURE=diagnostic line construction failed")
    }
    foreach ($diagnosticLine in $diagnosticLines) {
        $safeLine = ConvertTo-SafeDiagnosticText -Value $diagnosticLine
        try {
            if ($null -ne $Writer) {
                # Pass one completed string so braces, percent signs, and
                # quotes in error text can never become a format string.
                $Writer.WriteLine([string]$safeLine)
            }
            else {
                [Console]::Error.WriteLine([string]$safeLine)
            }
        }
        catch {
            try {
                [Console]::Error.WriteLine([string]("ERROR_DIAGNOSTICS_FALLBACK=" + $safeLine))
            }
            catch {
                try { Write-Host ([string]("ERROR_DIAGNOSTICS_FALLBACK=" + $safeLine)) } catch { }
            }
        }
    }
}

function Test-ErrorDiagnosticsSafe {
    $messages = @(
        "ordinary exception",
        "format token {0} and empty braces {}",
        "中文错误文本",
        "multi-line`nerror",
        'percent 100% and quoted ''text'' "text"'
    )
    foreach ($message in $messages) {
        $writer = New-Object System.IO.StringWriter
        try {
            $exception = [System.Exception]::new($message)
            $record = [System.Management.Automation.ErrorRecord]::new(
                $exception,
                "SyntheticDiagnostics",
                [System.Management.Automation.ErrorCategory]::NotSpecified,
                $null)
            Write-ErrorDiagnostics -ErrorRecord $record -Writer $writer
            if ([string]::IsNullOrWhiteSpace($writer.ToString())) {
                throw "Diagnostics writer produced no output."
            }
        }
        finally {
            $writer.Dispose()
        }
    }
    $nullWriter = New-Object System.IO.StringWriter
    try {
        Write-ErrorDiagnostics -ErrorRecord $null -Writer $nullWriter
        if ([string]::IsNullOrWhiteSpace($nullWriter.ToString())) {
            throw "Null ErrorRecord diagnostics produced no output."
        }
    }
    finally {
        $nullWriter.Dispose()
    }
}

function Invoke-CapturedProcess {
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [Parameter(Mandatory = $true)][AllowEmptyString()][AllowNull()][string]$Arguments,
        [Parameter(Mandatory = $true)][string]$StdoutPath,
        [Parameter(Mandatory = $true)][string]$StderrPath,
        [Parameter(Mandatory = $true)][string]$WorkingDirectory
    )
    $start = (Get-Date).ToUniversalTime()
    $stdout = ""
    $stderr = ""
    $exitCode = $null
    $launchError = ""
    $process = $null
    try {
        $info = [System.Diagnostics.ProcessStartInfo]::new()
        $info.FileName = $FilePath
        $info.Arguments = if ($null -eq $Arguments) { "" } else { [string]$Arguments }
        $info.WorkingDirectory = $WorkingDirectory
        $info.UseShellExecute = $false
        $info.CreateNoWindow = $true
        $info.RedirectStandardOutput = $true
        $info.RedirectStandardError = $true
        Write-Log "PROCESS_START file=$FilePath"
        $process = [System.Diagnostics.Process]::new()
        $process.StartInfo = $info
        if (-not $process.Start()) {
            throw "External process did not start: $FilePath"
        }
        $stdoutTask = $process.StandardOutput.ReadToEndAsync()
        $stderrTask = $process.StandardError.ReadToEndAsync()
        $process.WaitForExit()
        $stdout = $stdoutTask.GetAwaiter().GetResult()
        $stderr = $stderrTask.GetAwaiter().GetResult()
        $exitCode = $process.ExitCode
        Write-Log "PROCESS_EXIT file=$FilePath exit=$exitCode"
    }
    catch {
        $launchError = [string]$_.Exception.Message
        $stderr = $launchError
        Write-Log "PROCESS_CAPTURE_FAILURE file=$FilePath error=$launchError"
    }
    finally {
        if ($null -ne $process) {
            $process.Dispose()
        }
    }
    if ($null -eq $stdout) { $stdout = "" }
    if ($null -eq $stderr) { $stderr = "" }
    Write-NewTextFile -Path $StdoutPath -Text $stdout
    Write-NewTextFile -Path $StderrPath -Text $stderr
    return [pscustomobject]@{
        StartUtc = $start.ToString("o")
        EndUtc = (Get-Date).ToUniversalTime().ToString("o")
        ExitCode = $exitCode
        LaunchError = $launchError
    }
}

function Test-ProcessCaptureSafe {
    $captureDirectory = Join-Path $script:RunDir "capture_self_test"
    New-Item -ItemType Directory -Path $captureDirectory | Out-Null
    $powershellCommand = Get-Command powershell.exe -ErrorAction Stop
    $powershellPath = if ($powershellCommand.Path) { $powershellCommand.Path } else { $powershellCommand.Source }
    if (-not (Test-Path -LiteralPath $powershellPath -PathType Leaf)) {
        throw "PowerShell test executable is missing: $powershellPath"
    }
    $richStdout = Join-Path $captureDirectory "rich_stdout.log"
    $richStderr = Join-Path $captureDirectory "rich_stderr.log"
    $richCommand = "& { Write-Output 'capture normal {0} % 中文'; Write-Output 'capture line 2'; [Console]::Error.Write('capture stderr {} 100% 中文') }"
    $richArguments = '-NoProfile -NonInteractive -Command "' + $richCommand + '"'
    $richResult = Invoke-CapturedProcess -FilePath $powershellPath -Arguments $richArguments -StdoutPath $richStdout -StderrPath $richStderr -WorkingDirectory $ProjectRoot
    if ($richResult.ExitCode -ne 0) {
        throw "Capture self-test rich process failed with exit code $($richResult.ExitCode): $($richResult.LaunchError)"
    }
    $richOutText = [System.IO.File]::ReadAllText($richStdout)
    $richErrText = [System.IO.File]::ReadAllText($richStderr)
    if ($richOutText -notmatch "capture normal" -or $richOutText -notmatch "capture line 2") {
        throw "Capture self-test did not preserve normal/multiline stdout."
    }
    if ($richErrText -notmatch "capture stderr") {
        throw "Capture self-test did not preserve stderr."
    }
    $emptyStdout = Join-Path $captureDirectory "empty_stdout.log"
    $emptyStderr = Join-Path $captureDirectory "empty_stderr.log"
    $emptyResult = Invoke-CapturedProcess -FilePath $powershellPath -Arguments '-NoProfile -NonInteractive -Command "exit 0"' -StdoutPath $emptyStdout -StderrPath $emptyStderr -WorkingDirectory $ProjectRoot
    if ($emptyResult.ExitCode -ne 0) {
        throw "Capture self-test empty process failed with exit code $($emptyResult.ExitCode): $($emptyResult.LaunchError)"
    }
    if ([System.IO.File]::ReadAllText($emptyStdout) -ne "" -or [System.IO.File]::ReadAllText($emptyStderr) -ne "") {
        throw "Capture self-test empty process produced unexpected output."
    }
    Write-Log "TASK_OUTPUT_CAPTURE_NEVER_THROWS=PASS"
}

function Invoke-MatlabBatch {
    param(
        [Parameter(Mandatory = $true)][string]$Expression,
        [Parameter(Mandatory = $true)][string]$StdoutPath,
        [Parameter(Mandatory = $true)][string]$StderrPath
    )
    # ProcessStartInfo.Arguments is the Windows PowerShell 5.1-compatible
    # process contract; the MATLAB expression contains single-quoted strings.
    $escapedExpression = $Expression.Replace('"', '\"')
    $arguments = '-batch "' + $escapedExpression + '"'
    return Invoke-CapturedProcess -FilePath $MatlabExecutable -Arguments $arguments -StdoutPath $StdoutPath -StderrPath $StderrPath -WorkingDirectory $ProjectRoot
}

function New-FallbackReceipt {
    param(
        [Parameter(Mandatory = $true)][object]$Task,
        [Parameter(Mandatory = $true)][string]$OutputDir,
        [Parameter(Mandatory = $true)][string]$Status,
        [Parameter(Mandatory = $true)][string]$Reason,
        [Parameter(Mandatory = $true)][string]$ReceiptPath,
        [int]$ExitCode = -1,
        [string]$StartUtc = "",
        [string]$EndUtc = ""
    )
    $receipt = [ordered]@{
        sequence = $Task.Sequence
        weather = $Task.Weather
        scene = $Task.Scene
        prn = $Task.PRN
        channel = $Task.Channel
        execution_status = "NOT_EXECUTED"
        matlab_exit_code = $ExitCode
        stage0_status = "NOT_RUN"
        valid_nav_symbols = ""
        complete_windows = ""
        stage1_status = "NOT_RUN"
        scanned_windows = ""
        selected_windows = ""
        stage2_status = "NOT_RUN"
        stage2_windows = ""
        selected_l_ge_2 = ""
        selected_l_ge_3 = ""
        stage3_status = "NOT_RUN"
        reliable_centers = ""
        stage4_status = "NOT_RUN"
        joint_results = ""
        joint_valid_rows = ""
        confirmed_events = ""
        confirmed_multipath_paths = ""
        relative_phase_available = "NOT_APPLICABLE"
        darkroom_parameters_ready = "NO"
        overall_status = $Status
        failure_reason = $Reason
        output_dir = $OutputDir
        stdout_path = ""
        stderr_path = ""
        start_utc = $StartUtc
        end_utc = $EndUtc
        missing_outputs = @()
        parameter_rows = @()
    }
    Write-NewJson -Path $ReceiptPath -Value $receipt
    return $receipt
}

function Invoke-QaHelper {
    param(
        [Parameter(Mandatory = $true)][string]$TaskRecordPath,
        [Parameter(Mandatory = $true)][string]$ReceiptPath
    )
    $helperOutput = @(& $script:PythonExecutable $QaHelper --task-record $TaskRecordPath --output-receipt $ReceiptPath 2>&1)
    $helperExit = $LASTEXITCODE
    foreach ($line in $helperOutput) {
        Write-Log ("QA_HELPER " + [string]$line)
    }
    if ($helperExit -ne 0) {
        throw "QA helper failed with exit code $helperExit for $TaskRecordPath"
    }
    return Get-Content -LiteralPath $ReceiptPath -Raw | ConvertFrom-Json
}

function Write-TaskRecord {
    param(
        [Parameter(Mandatory = $true)][object]$Task,
        [Parameter(Mandatory = $true)][object]$ProcessResult,
        [Parameter(Mandatory = $true)][string]$OutputDir,
        [Parameter(Mandatory = $true)][string]$Expression,
        [Parameter(Mandatory = $true)][string]$StdoutPath,
        [Parameter(Mandatory = $true)][string]$StderrPath,
        [Parameter(Mandatory = $true)][string]$Path
    )
    $record = [ordered]@{
        sequence = $Task.Sequence
        weather = $Task.Weather
        scene = $Task.Scene
        prn = $Task.PRN
        channel = $Task.Channel
        output_dir = $OutputDir
        matlab_exit_code = $ProcessResult.ExitCode
        start_utc = $ProcessResult.StartUtc
        end_utc = $ProcessResult.EndUtc
        stdout_path = $StdoutPath
        stderr_path = $StderrPath
        launch_error = $ProcessResult.LaunchError
        failure_reason = if ($ProcessResult.LaunchError) { $ProcessResult.LaunchError } else { "" }
        matlab_expression = $Expression
        production_sha256 = $script:ProductionHashBefore
        preflight_sha256 = $script:PreflightHashBefore
        raw_iq_opened_by_runner = $false
        gold_labels_used = $false
    }
    Write-NewJson -Path $Path -Value $record
    return $record
}

$globalStop = $false
$runResult = $null
$summaryResult = $null
try {
    if (-not (Test-Path -LiteralPath $ProjectRoot -PathType Container)) {
        throw "Project root is missing: $ProjectRoot"
    }
    if (-not (Test-Path -LiteralPath $MonitorRoot -PathType Container)) {
        New-Item -ItemType Directory -Path $MonitorRoot | Out-Null
    }
    $script:ProductionHashBefore = Assert-ProductionFrozen
    Assert-RainInterface
    if (-not (Test-Path -LiteralPath $PreflightCsv -PathType Leaf)) {
        throw "Static preflight CSV is missing: $PreflightCsv"
    }
    $script:PreflightHashBefore = Get-FileSha256 -Path $PreflightCsv
    $preflightRows = @(Import-Csv -LiteralPath $PreflightCsv)
    if ($preflightRows.Count -ne 9) {
        throw "Expected 9 static preflight rows, found $($preflightRows.Count)."
    }
    if (-not (Test-Path -LiteralPath $QaHelper -PathType Leaf)) {
        throw "QA helper is missing: $QaHelper"
    }
    $pythonCommand = Get-Command python.exe -ErrorAction Stop
    $script:PythonExecutable = if ($pythonCommand.Path) { $pythonCommand.Path } else { $pythonCommand.Source }
    if (-not (Test-Path -LiteralPath $script:PythonExecutable -PathType Leaf)) {
        throw "Resolved Python executable is not a file: $script:PythonExecutable"
    }
    & $script:PythonExecutable --version
    if ($LASTEXITCODE -ne 0) {
        throw "Python version check failed."
    }
    Acquire-GlobalRunnerMutex
    # Formal and dry-run modes share the complete pre-MATLAB initialization
    # path.  Dry-run stops only after this block and before Invoke-MatlabBatch.
    $script:RunDir = New-UniqueRunDirectory
    $script:MasterLog = Join-Path $script:RunDir "master.log"
    $summaryDirectory = Join-Path $script:RunDir "summary"
    New-Item -ItemType Directory -Path $summaryDirectory | Out-Null
    $script:QaCsvPath = Join-Path $summaryDirectory "rain_sage_execution_qa_20260818.csv"
    $script:ParametersCsvPath = Join-Path $summaryDirectory "rain_sage_darkroom_parameters_v1.csv"
    $script:QaReportPath = Join-Path $summaryDirectory "RAIN_SAGE_QA_REPORT_20260818.md"
    $script:MeetingReportPath = Join-Path $summaryDirectory "TOMORROW_MEETING_RAIN_SAGE_RESULTS.md"
    Write-NewTextFile -Path $script:MasterLog -Text ("Rain overnight runner started $(Get-Date -Format o)" + [Environment]::NewLine)
    New-Item -ItemType Directory -Path (Join-Path $script:RunDir "receipts") | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $script:RunDir "task_logs") | Out-Null
    Write-NewJson -Path (Join-Path $script:RunDir "task_schedule.json") -Value $Tasks
    Test-ErrorDiagnosticsSafe
    Test-ProcessCaptureSafe
    $script:FormalInitializationComplete = $true
    Write-Log "FORMAL_INITIALIZATION_PATH=PASS"
    Write-Log "ERROR_DIAGNOSTICS_NEVER_THROWS=PASS"
    Write-Log "PRODUCTION_SHA_BEFORE=$script:ProductionHashBefore"
    Write-Log "PREFLIGHT_SHA256=$script:PreflightHashBefore"
    Write-Log "SUMMARY_NAMESPACE=$summaryDirectory"
    Write-Log "LEGACY_SUMMARY_ROOT_FILES_PRESERVED=YES"
    Write-Log "RAIN_MATLAB_SYNTAX_SMOKE=PASS (normal-user evidence; not rerun)"
    Write-Log "TASK_COUNT=$($Tasks.Count); EXECUTION_POLICY=SERIAL; RESUME=false; NEW_ONLY=true"
    if ($DryRun) {
        $plannedTasks = @()
        foreach ($task in $Tasks) {
            $currentHash = Assert-ProductionFrozen
            if ($currentHash -ne $script:ProductionHashBefore) {
                throw "Production SHA changed during dry-run."
            }
            if ((Get-FileSha256 -Path $PreflightCsv) -ne $script:PreflightHashBefore) {
                throw "Static preflight CSV changed during dry-run."
            }
            $row = Assert-PreflightRow -Task $task -Rows $preflightRows
            $outputDir = Assert-ExpectedOutputNamespace -Task $task -OutputDir ([string]$row.output_dir)
            if (Test-Path -LiteralPath $outputDir) {
                throw "Dry-run rejected: output namespace already exists: $outputDir"
            }
            $expression = New-MatlabExpression -Task $task
            $plannedTasks += [pscustomobject]@{
                Sequence = $task.Sequence
                Task = "$($task.Scene)/$($task.PRN)/ch$($task.Channel)"
                Output = $outputDir
                MatlabExpression = $expression
            }
        }
        $script:DryRunPlan = $plannedTasks
        Write-NewJson -Path (Join-Path $script:RunDir "dry_run_plan.json") -Value ([ordered]@{
                mode = "DRY_RUN_FORMAL_INITIALIZATION"
                formal_initialization_path = "PASS"
                matlab_started = $false
                raw_iq_opened = $false
                sage_executed = $false
                production_sha256 = $script:ProductionHashBefore
                preflight_sha256 = $script:PreflightHashBefore
                tasks = $plannedTasks
            })
        $afterDryRunHash = Assert-ProductionFrozen
        if ($afterDryRunHash -ne $script:ProductionHashBefore) {
            throw "Production SHA changed at dry-run completion."
        }
        Write-Output "OVERNIGHT_RUNNER_DRY_RUN=PASS"
        Write-Output "FORMAL_INITIALIZATION_PATH=PASS"
        Write-Output "FORMAL_PATH_RUNTIME_CHECK=PASS"
        Write-Output "ERROR_DIAGNOSTICS_NEVER_THROWS=PASS"
        Write-Output "TASK_OUTPUT_CAPTURE_NEVER_THROWS=PASS"
        Write-Output "MATLAB_STARTED=NO"
        Write-Output "RAW_IQ_OPENED=NO"
        Write-Output "SAGE_EXECUTED=NO"
        Write-Output "OUTPUT_SAGE_CREATED=NO"
        Write-Output "TASK_COUNT=$($plannedTasks.Count)"
        foreach ($planned in $plannedTasks) {
            Write-Output ("DRY_RUN_TASK={0} {1} OUTPUT={2}" -f $planned.Sequence, $planned.Task, $planned.Output)
            Write-Output ("DRY_RUN_MATLAB_EXPRESSION={0}" -f $planned.MatlabExpression)
        }
        exit 0
    }
    $executionIdentity = Assert-NormalUserExecutionIdentity
    Write-Log "EXECUTION_IDENTITY=$executionIdentity"

    foreach ($task in $Tasks) {
        if ($globalStop) { break }
        try {
            $currentHash = Assert-ProductionFrozen
            if ($currentHash -ne $script:ProductionHashBefore) {
                throw "Production SHA changed during overnight run."
            }
            if ((Get-FileSha256 -Path $PreflightCsv) -ne $script:PreflightHashBefore) {
                throw "Static preflight CSV changed during overnight run."
            }
            $row = Assert-PreflightRow -Task $task -Rows $preflightRows
            $outputDir = Assert-ExpectedOutputNamespace -Task $task -OutputDir ([string]$row.output_dir)
            $receiptPath = Join-Path $script:RunDir ("receipts\task_{0:D2}.json" -f $task.Sequence)
            if (Test-Path -LiteralPath $outputDir) {
                $blocked = New-FallbackReceipt -Task $task -OutputDir $outputDir -Status "INPUT_BLOCKED" -Reason "output_namespace_already_exists_new_only" -ReceiptPath $receiptPath
                Write-Log "TASK=$($task.Sequence) $($task.Scene)/$($task.PRN) INPUT_BLOCKED output exists; no MATLAB call."
                if ($task.Sequence -eq 1) { $globalStop = $true }
                continue
            }
            $expression = New-MatlabExpression -Task $task
            $stdoutPath = Join-Path $script:RunDir ("task_logs\{0}_{1}_stdout.log" -f $task.Weather, $task.PRN)
            $stderrPath = Join-Path $script:RunDir ("task_logs\{0}_{1}_stderr.log" -f $task.Weather, $task.PRN)
            Write-Log "TASK=$($task.Sequence) START $($task.Scene)/$($task.PRN)/ch$($task.Channel) output=$outputDir"
            Write-Log "TASK=$($task.Sequence) MATLAB_EXPRESSION=$expression"
            $processResult = Invoke-MatlabBatch -Expression $expression -StdoutPath $stdoutPath -StderrPath $stderrPath
            $taskRecordPath = Join-Path $script:RunDir ("task_logs\{0}_{1}_record.json" -f $task.Weather, $task.PRN)
            Write-TaskRecord -Task $task -ProcessResult $processResult -OutputDir $outputDir -Expression $expression -StdoutPath $stdoutPath -StderrPath $stderrPath -Path $taskRecordPath | Out-Null
            try {
                $qaReceipt = Invoke-QaHelper -TaskRecordPath $taskRecordPath -ReceiptPath $receiptPath
                Write-Log "TASK=$($task.Sequence) END status=$($qaReceipt.overall_status) exit=$($qaReceipt.matlab_exit_code) events=$($qaReceipt.confirmed_events) paths=$($qaReceipt.confirmed_multipath_paths)"
                if ($qaReceipt.overall_status -in @("SOFTWARE_FAIL", "INPUT_BLOCKED")) {
                    $script:ExitCode = 1
                }
                if ($task.Sequence -eq 1 -and $qaReceipt.overall_status -notin @("PASS_WITH_CONFIRMED_MULTIPATH", "PASS_NO_CONFIRMED_MULTIPATH")) {
                    Write-Log "GLOBAL_STOP: Clear G24 did not complete a valid Stage0-Stage4 run."
                    $globalStop = $true
                }
            }
            catch {
                Write-Log "TASK=$($task.Sequence) QA_HELPER_FAILURE=$($_.Exception.Message)"
                $script:ExitCode = 1
                if (-not (Test-Path -LiteralPath $receiptPath)) {
                    New-FallbackReceipt -Task $task -OutputDir $outputDir -Status "SOFTWARE_FAIL" -Reason "qa_helper_failure" -ReceiptPath $receiptPath -ExitCode $processResult.ExitCode | Out-Null
                }
                if ($task.Sequence -eq 1) { $globalStop = $true }
            }
            $afterTaskHash = Assert-ProductionFrozen
            if ($afterTaskHash -ne $script:ProductionHashBefore) {
                throw "Production SHA changed after task $($task.Sequence)."
            }
        }
        catch {
            Write-Log "TASK=$($task.Sequence) FAILURE=$($_.Exception.Message)"
            $script:ExitCode = 1
            $receiptPath = Join-Path $script:RunDir ("receipts\task_{0:D2}.json" -f $task.Sequence)
            $outputDir = Join-Path $ProjectRoot ("scenes\{0}\sage_results\rain_sage_v1\{1}" -f $task.Scene, $task.PRN)
            if (-not (Test-Path -LiteralPath $receiptPath)) {
                New-FallbackReceipt -Task $task -OutputDir $outputDir -Status "SOFTWARE_FAIL" -Reason $_.Exception.Message -ReceiptPath $receiptPath | Out-Null
            }
            if ($task.Sequence -eq 1) {
                $globalStop = $true
            }
        }
    }
}
catch {
    $globalStop = $true
    $script:ExitCode = 1
    Write-ErrorDiagnostics -ErrorRecord $_
    if ($null -ne $script:MasterLog) {
        Write-Log "RUNNER_FATAL=$($_.Exception.Message)"
    }
}
finally {
    if ($null -ne $script:RunDir) {
        $qaReport = $script:QaReportPath
        $meetingReport = $script:MeetingReportPath
        if ($DryRun) {
            Write-Log "DRY_RUN_SUMMARY_HELPER=NOT_RUN"
            Write-Log "DRY_RUN_OUTPUT_NAMESPACE=NO_SAGE_OUTPUT_CREATED"
        }
        else {
            try {
                $summaryOutput = @(& $script:PythonExecutable $QaHelper --summarize --run-dir $script:RunDir --qa-csv $script:QaCsvPath --parameters-csv $script:ParametersCsvPath --report $qaReport --meeting-report $meetingReport 2>&1)
                foreach ($line in $summaryOutput) { Write-Log ("SUMMARY_HELPER " + [string]$line) }
                if ($LASTEXITCODE -ne 0) { Write-Log "SUMMARY_HELPER_EXIT=$LASTEXITCODE" }
            }
            catch {
                Write-Log "SUMMARY_FAILURE=$($_.Exception.Message)"
                $script:ExitCode = 1
            }
        }
        $productionAfter = "UNAVAILABLE"
        $productionDiff = "UNAVAILABLE"
        try {
            $productionAfter = Get-FileSha256 -Path $ProductionEntry
            $productionDiff = (@(& git -C $ProjectRoot diff -- $ProductionEntry) -join [Environment]::NewLine)
        }
        catch {
            Write-Log "PRODUCTION_POSTCHECK_FAILURE=$($_.Exception.Message)"
        }
        $unchanged = ($productionAfter -eq $script:ProductionHashBefore -and [string]::IsNullOrWhiteSpace($productionDiff))
        $unchangedText = if ($unchanged) { "YES" } else { "NO" }
        $terminalStatus = if ($globalStop) { "GLOBAL_SOFTWARE_FAILURE_OR_STOP" } else { "SEQUENTIAL_RUN_FINISHED" }
        Write-Log "PRODUCTION_SHA_AFTER=$productionAfter"
        Write-Log "PRODUCTION_UNCHANGED=$unchangedText"
        Write-Log "FILES_DELETED_COUNT=0"
        Write-Log "FILES_MOVED_TO_TRASH=0"
        Write-Log "TRASH_DIRECTORY_PRESERVED=YES"
        Write-Log "NO_DELETE_POLICY_VIOLATION=YES"
        Write-Log "RUN_STATUS=$terminalStatus"
        Write-Output "RUNNER_PATH=$PSCommandPath"
        Write-Output "RUNNER_LOG_DIRECTORY=$script:RunDir"
        Write-Output "QA_REPORT_PATH=$qaReport"
        Write-Output "MEETING_REPORT_PATH=$meetingReport"
        Write-Output "PRODUCTION_SHA_BEFORE=$script:ProductionHashBefore"
        Write-Output "PRODUCTION_SHA_AFTER=$productionAfter"
        Write-Output "PRODUCTION_UNCHANGED=$unchangedText"
        if ($DryRun) {
            Write-Output "FORMAL_INITIALIZATION_PATH=PASS"
            Write-Output "FORMAL_PATH_RUNTIME_CHECK=PASS"
            Write-Output "TASK_OUTPUT_CAPTURE_NEVER_THROWS=PASS"
            Write-Output "MATLAB_STARTED=NO"
            Write-Output "RAW_IQ_OPENED=NO"
            Write-Output "SAGE_EXECUTED=NO"
        }
        Write-Output "FILES_DELETED_COUNT=0"
        Write-Output "FILES_MOVED_TO_TRASH=0"
        Write-Output "TRASH_DIRECTORY_PRESERVED=YES"
        Write-Output "NO_DELETE_POLICY_VIOLATION=YES"
    }
    if ($script:MutexAcquired) {
        $script:GlobalMutex.ReleaseMutex()
        $script:GlobalMutex.Dispose()
        $script:MutexAcquired = $false
        Write-Output "GLOBAL_MUTEX_RELEASED=YES"
    }
}

if ($script:ExitCode -ne 0) {
    exit $script:ExitCode
}
