function result = run_rain_sage_pipeline(sceneId, prn, varargin)
%RUN_RAIN_SAGE_PIPELINE Rain-specific SAGE entry and fail-closed preflight.
%
% Rain MVP does not require NMEA/PVT/RINEX/trajectory/geometry. This entry
% owns the Rain adapter and calls the branch-local Rain Stage1-Stage4 copy.
%
% Preflight example:
%   run_rain_sage_pipeline("F1023_clear", "G24", ...
%       "TrackingChannel", 10, ...
%       "ProjectRoot", "E:\GNSS_Multipath_Project", ...
%       "Resume", false)
%
% Stage0-only capture, after Commander approval:
%   ... "Stage0Only", true

scriptDir = fileparts(mfilename("fullpath"));
defaultProjectRoot = fileparts(fileparts(fileparts(scriptDir)));
rainDirectory = scriptDir;
assert(isfile(fullfile(rainDirectory, "run_rain_sage_stage1_stage4.m")) && ...
    isfile(fullfile(rainDirectory, "default_rain_sage_configuration.m")) && ...
    isfile(fullfile(rainDirectory, "compute_rain_doppler_bound.m")), ...
    "Standalone Rain SAGE files are missing: %s", rainDirectory);
addpath(rainDirectory, "-begin");
parser = inputParser;
addRequired(parser, "sceneId", @(v) ischar(v) || (isstring(v) && isscalar(v)));
addRequired(parser, "prn", @(v) isnumeric(v) || ischar(v) || ...
    (isstring(v) && isscalar(v)));
addParameter(parser, "TrackingChannel", [], @(v) isnumeric(v) && ...
    isscalar(v) && isfinite(v) && v == round(v) && v >= 0);
addParameter(parser, "ProjectRoot", defaultProjectRoot, @(v) ...
    ischar(v) || (isstring(v) && isscalar(v)));
addParameter(parser, "Resume", false, @(v) ...
    (islogical(v) || isnumeric(v)) && isscalar(v));
addParameter(parser, "PreflightOnly", true, @(v) ...
    (islogical(v) || isnumeric(v)) && isscalar(v));
addParameter(parser, "Stage0Only", false, @(v) ...
    (islogical(v) || isnumeric(v)) && isscalar(v));
parse(parser, sceneId, prn, varargin{:});
options = parser.Results;

assert(~logical(options.Resume), ...
    "Rain pipeline is new-only; Resume=true is rejected.");
assert(~isempty(options.TrackingChannel), ...
    "TrackingChannel must be supplied explicitly.");

[prnNumber, prnLabel] = normalizeRainPrn(options.prn);
sceneId = string(options.sceneId);
projectRoot = string(options.ProjectRoot);
outputDir = fullfile(projectRoot, "scenes", sceneId, ...
    "sage_results", "rain_sage_v1", prnLabel);
assert(~isfolder(outputDir) && ~isfile(outputDir), ...
    "Rain output namespace already exists; new-only refuses reuse: %s", outputDir);

writeStage0 = logical(options.Stage0Only) || ~logical(options.PreflightOnly);
stage0 = build_rain_stage0(sceneId, prnNumber, ...
    "TrackingChannel", options.TrackingChannel, ...
    "ProjectRoot", projectRoot, ...
    "OutputDir", outputDir, ...
    "WriteOutputs", writeStage0);

result = struct( ...
    "status", "RAIN_PREFLIGHT_ONLY", ...
    "scene_id", sceneId, ...
    "prn", prnLabel, ...
    "prn_number", prnNumber, ...
    "tracking_channel", double(options.TrackingChannel), ...
    "sample_rate_hz", 10230000, ...
    "output_namespace", string(outputDir), ...
    "stage0_symbol_count", height(stage0.symbolCatalog), ...
    "stage0_window_count", height(stage0.windowCatalog), ...
    "nmea_required", false, ...
    "pvt_required", false, ...
    "rinex_required", false, ...
    "trajectory_required", false, ...
    "geometry_required", false, ...
    "elevation_conditioning", false, ...
    "stage1_stage4_implementation", "standalone_rain_branch_local");

if logical(options.Stage0Only)
    result.status = "RAIN_STAGE0_ONLY_READY";
elseif ~logical(options.PreflightOnly)
    coreResult = run_rain_sage_stage1_stage4( ...
        stage0.windowCatalog, stage0.symbolCatalog, stage0.raw_file, ...
        outputDir, stage0.cfg);
    result.status = "RAIN_STAGE1_STAGE4_COMPLETED";
    result.doppler_sign_used = coreResult.dopplerSignUsed;
    result.stage1_scanned_windows = height(coreResult.stage1Table);
    result.stage1_candidate_windows = numel(coreResult.candidateIndices);
    result.stage2_fits = numel(coreResult.stage2Fits);
    result.stage2_model_rows = height(coreResult.modelTable);
    result.stage2_selected_rows = height(coreResult.selectedTable);
    result.stage3_reliable_centers = height(coreResult.reliableTable);
    result.stage4_joint_rows = height(coreResult.jointSummaryTable);
    result.stage4_joint_paths = height(coreResult.jointPathTable);
end
end


function [prnNumber, prnLabel] = normalizeRainPrn(prn)
if isnumeric(prn)
    prnNumber = double(prn);
else
    text = upper(strtrim(string(prn)));
    text = erase(text, ["GPS", "PRN", "G"]);
    prnNumber = str2double(text);
end
assert(isfinite(prnNumber) && prnNumber == round(prnNumber) ...
    && prnNumber >= 1 && prnNumber <= 32, ...
    "Rain PRN must identify GPS 1 through 32.");
prnLabel = compose("G%02d", prnNumber);
end
